// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FridgeOpeningController from "./fridge_opening_controller"
application.register("fridge-opening", FridgeOpeningController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
